meta_product_name: "whatcanieat?"
meta_title: "What can I eat? - Stop wasting your food, cook what you have!"
meta_description: "An app that prevents food waste and encourages users to connect and utilise what they already have"
meta_image: "final_logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
